FROM elixir:1.14
RUN apt-get update -y && \
        apt-get install -y \
        postgresql-client \
        inotify-tools \
        npm \
        build-essential \
        git \
        libsqlite3-dev \
        libsodium-dev

RUN npm install -g esbuild

RUN mkdir /app /archive
WORKDIR /app
RUN useradd -u 1000 rawwater -m && \
        chown -R rawwater:rawwater /app
USER rawwater:rawwater

RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs /app/mix.exs

# fine-grained access token with contents and metadata read-only perms on ctf_tickets_elixir
RUN git config --global url."https://vito-lbs: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@github.com/".insteadOf "https://github.com" && \
        mix deps.get && \
        mix deps.compile
COPY --chown=rawwater:rawwater . /app
CMD mix phx.server
