[package]
name = "sfm-sys"
version = "0.1.0"
edition = "2021"

links = "sfm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"

[build-dependencies]
cc = "1.0"
